version: "3"

networks:
  analyze:
    external: false

services:
  analyze_api:
    build: 
      context: ./api
      args:
        COOKIE: test
        ALLOWED_URL: "*"
    environment:
      - POSTGRES_URL=ecto://test:test@analyze_db:5432/test?sslmode=disable
      - ALLOWED_URL=https://freelytics.net
    ports:
      - "8080:8080"
    depends_on:
      - analyze_db
    networks:
      - analyze
    restart: always
    command: "foreground"
  analyze_db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - analyze
    restart: always
